Skyscanner/backpack-android

Backpack/build.gradle
app/build.gradle
app/src/main/java/net/skyscanner/backpack/MainActivity.kt

This removed the kotlin files from the javadocs task and fix all the warning while running the build from the cli

[NoJira] fix build and remove warning while running gradle from cli

---

.release-it.json
Backpack/build.gradle
CONTRIBUTING.md
README.md
badge/build.gradle
base.gradle
build.gradle
core/build.gradle
package.json
release.js

Adding publishing logic for jitpack. The Backpack dependecies can now be included using 
`implementation 'com.github.Skyscanner:backpack-android:no-jira-publish-tasks-SNAPSHOT' `
After release 
`implementation 'com.github.Skyscanner:backpack-android:0.2.2' `
or as individual packages:
`implementation 'com.github.Skyscanner.backpack-android:badge:0.2.2' `

[No-JIRA] Publish task for modules

---

Backpack/build.gradle
CONTRIBUTING.md
base.gradle
build.gradle
package.json

It looks like this:
The little `source` link at the top links to the source code on github \o/
It can be generated locally with `npm run docs` and viewed with `chrome build/docs/backpack-android/index.html`
To configure the outputFolder `npm run docs -- -PdokkaOutput=/path/to/folder`

[BPK-1836] Config API docs

---

.travis.yml
Backpack/build.gradle
Backpack/src/main/java/net/skyscanner/backpack/panel/BpkPanel.kt
Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt
build.gradle

Updates minSDK to 19. Changes include
- Use `ResourceCompat` to get resources for backward compatibility
Update kotlin version from `1.2.51` to `1.2.60`. Causes minor syntax change for `@IntDef` 
Update `Junit` and `Espresso` dependencies

[BPK-1920] Update dependencies and minSDK

---

app/build.gradle
app/src/main/java/net/skyscanner/backpack/demo/ComponentDetailActivity.kt
app/src/main/java/net/skyscanner/backpack/demo/ComponentDetailFragment.kt
app/src/main/res/layout/activity_component_detail.xml

Removing the header image and collapsing-toolbar from stories

Remove header image and Image loading library

---

app/src/main/AndroidManifest.xml
app/src/main/java/net/skyscanner/backpack/demo/BackpackDemoApplication.kt

Fixes a crash on API-19 while loading vector icons. This fix enables using vector resources using compatibility library.
see https://stackoverflow.com/a/42956161

[no-jira] Icons bugfix for API 19

---

Backpack/src/androidTest/java/net/skyscanner/backpack/button/BpkButtonTest.kt
Backpack/src/main/java/net/skyscanner/backpack/button/BpkButton.kt
app/src/main/java/net/skyscanner/backpack/demo/stories/ButtonStory.kt
app/src/main/res/layout/fragment_button.xml

**Issue:** with the current API if you set isEnabled from code (f.x. disabling the button upon certain condition in code, and not from XML) then it had no effect
**Cause:** `setEnabled` is called on the AppCompatButton API and the `setup()` is not called.
**Solution:** Overriding the `setEnabled` API call and triggering a `setup()` call after the state change (similar to how we do it after any custom property change - icon, type)
I also added a hidden click listener on the icon button on each story so we can flip the state of the disabled button to show this functionality. *If you prefer, it can be removed.*

[BpkButton] should be possible to set isEnabled from code

---

build.gradle

Not using any new features of Kotlin 1.3 yet. This PR is for being in sync with dependencies on the client apps.

Kotlin version bump

---

Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt
Backpack/src/main/res/values/attrs.xml
app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
app/src/main/res/layout/fragment_text_drawables.xml

Support using `drawableTint` on BpkText for android API < 23
The developer needs to change from 
`android:drawableTint="@color/bpkRed500"` to 
`app:drawableTint="@color/bpkRed500"`
in java/kotlin use
`view.setDrawableTint(ContextCompat.getColor(holder.view.context,R.color.bpkGreen600))`
This also supports tint for `drawableLeft` and `drawableRight`

[BPK-2141] Support tint for drawables on BpkText

---

Backpack/build.gradle
Backpack/src/main/java/net/skyscanner/backpack/util/BpkInterceptor.kt
CONTRIBUTING.md
app/src/main/java/net/skyscanner/backpack/demo/BackpackDemoApplication.kt
app/src/main/java/net/skyscanner/backpack/demo/BpkBaseActivity.kt
app/src/main/java/net/skyscanner/backpack/demo/ComponentDetailActivity.kt
app/src/main/java/net/skyscanner/backpack/demo/MainActivity.kt
app/src/main/java/net/skyscanner/backpack/demo/data/SharedPreferences.kt
app/src/main/res/values/strings.xml

Adds debug markers to all Backpack views.
Installation instructions:
Add the interceptor inr the Application class's `onCreate` as follows:
```
ViewPump.init(ViewPump.builder()
.addInterceptor(BpkInterceptor())
.build())
```
Add the contextWrapper to the base activity as:
```
override fun attachBaseContext(newBase: Context) {
super.attachBaseContext(ViewPumpContextWrapper.wrap(newBase))
}
```
Caveats:
- Introduces the dependecy on `inflaterX` in the app. This can be moved to test dependency if required
- Adds another function in the all the base class activities.

[Bpk-2080] Add debug markers 

---

Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarControllerTest.kt
Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarController.kt
UNRELEASED.md

BPK calendar date changing mechanism is updated with new logic (every selection after a range defined clears the previously selected range).

Improve BPK calendar date selection

---

Backpack/src/main/java/net/skyscanner/backpack/calendar/BpkCalendar.kt
Backpack/src/main/java/net/skyscanner/backpack/calendar/view/CalendarView.kt

Removing all the logic we had to make the RN bridge work, I'm changing the bridge implementation to handle layout in a better way and moving all "hacks" to that code, so the native Android version can stay clean.
As an added benefit the year pill now works when rendered in the same UI thread 🎉 

[BPK-2340] Fix RN rendering

---

Backpack/src/main/java/net/skyscanner/backpack/button/BpkButton.kt
Backpack/src/main/java/net/skyscanner/backpack/toggle/BpkSwitch.kt
Backpack/src/main/java/net/skyscanner/backpack/util/ThemesUtil.kt
Backpack/src/main/res/values/attrs.xml
app/src/main/java/net/skyscanner/backpack/demo/BpkBaseActivity.kt
app/src/main/java/net/skyscanner/backpack/demo/SettingsActivity.kt
app/src/main/res/values/themes.xml
docs/THEMING.md

This adds `bpkThemeOverlay` attribute and the `ThemeOverlayEnforcement` class to wrap a context and indicate `bpkThemeOverlay` should be used.
This means we can now just define `bpkThemeOverlay` in the current app theme and wrap the context with `ThemeOverlayEnforcement` based on a config flag during runtime to enforce its usage.

[NO-JIRA] Overlay wrapper

---

Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/view/MonthViewKtTest.kt
Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/view/NonDrawnDaysOffset.kt
Backpack/src/main/java/net/skyscanner/backpack/calendar/model/CalendarColoring.kt
Backpack/src/main/java/net/skyscanner/backpack/calendar/model/CalendarDay.kt
Backpack/src/main/java/net/skyscanner/backpack/calendar/view/MonthView.kt
Backpack/src/main/java/net/skyscanner/backpack/calendar/view/WeekdayHeaderView.kt
Backpack/src/main/res/layout/view_bpk_calendar_weekday_header.xml
app/src/androidTest/java/net/skyscanner/backpack/calendar/BpkCalendarTest.kt
app/src/main/java/net/skyscanner/backpack/demo/data/ExampleBpkCalendarController.kt
app/src/main/java/net/skyscanner/backpack/demo/stories/ColoredCalendarStory.kt

- Fixed 1 px white line in range when 2 dates dates selected besides each other (Pixel 2 XL)
- Introduced a new selected color and made original one optional (non-breaking)
- Unavailable dates are not useful for the first month -> we do not draw them
- Days header(Mon,Tue,Wed, ...) at the top were not perfectly aligned to days in the calendar
- Reduced days header padding (lg->base)
- Use the locale from the controller for first day of week everywhere

Colored calendar refinements

---

Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarController.kt
package.json

This also fixes a small bug in the calendar (that was happening because we were not running snapshots before release)
This ensures we run all snapshot tests before release. We run them on CI too with the exception of `FlakyTests` which fail very often because of timeouts. Those we still want to check locally before releasing.

[NO-JIRA] Correctly run snapshots before release

---

Backpack/src/main/java/net/skyscanner/backpack/util/BpkViewPumpContextWrapper.kt
app/src/main/java/net/skyscanner/backpack/demo/BpkBaseActivity.kt

Disable `ViewPump` on Android-Q for now. This means the highlights can still be used on emulators and devices running a stable version of Android upto API-28

[BPK-2390] Disable ViewPump on Android Q

---

Backpack/src/main/java/net/skyscanner/backpack/calendar/view/CalendarView.kt
UNRELEASED.md

The MonthHeader views is already transparent but the calendar was setting the background to `white` making it impossible to use in a view with a different background colour

[NO-JIRA] Fix calendar background

---

Backpack/src/main/java/net/skyscanner/backpack/button/BpkButton.kt
Backpack/src/main/java/net/skyscanner/backpack/calendar/BpkCalendar.kt
Backpack/src/main/java/net/skyscanner/backpack/chip/BpkChip.kt
Backpack/src/main/java/net/skyscanner/backpack/gradient/BpkGradients.kt
Backpack/src/main/java/net/skyscanner/backpack/spinner/BpkSpinner.kt
Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt
Backpack/src/main/java/net/skyscanner/backpack/toggle/BpkSwitch.kt
Backpack/src/main/java/net/skyscanner/backpack/util/ThemesUtil.kt
Backpack/src/main/res/drawable/bpk_button_state_animator.xml
UNRELEASED.md
app/src/androidTest/java/net/skyscanner/backpack/TestUtils.kt
app/src/main/java/net/skyscanner/backpack/demo/BackpackDemoApplication.kt
app/src/main/java/net/skyscanner/backpack/demo/BpkBaseActivity.kt
app/src/main/java/net/skyscanner/backpack/demo/SettingsActivity.kt
app/src/main/java/net/skyscanner/backpack/demo/ThemeApplier.kt
app/src/main/java/net/skyscanner/backpack/demo/stories/IconsStory.kt
app/src/main/res/values/themes.xml

Removing some stuff we do not use anymore, mainly `ThemeOverlayEnforcement`. The overlay approach didn't work as expected in the app and we moved to a different one. This mimics what is in use in the app at the moment.

[NO-JIRA] Clean up theming

---

Backpack/src/main/java/net/skyscanner/backpack/toggle/BpkSwitch.kt
UNRELEASED.md

Previous approach causes problems/confusion when our components are extended and we have moved away from it in other components. Switch was the only component still using this approach.

[NO-JIRA] Change switch theming approach

---

Backpack/src/main/java/net/skyscanner/backpack/util/BpkTheme.kt

This annotation can assist when using the getPrimaryColor method so users know what int they get in return.

Add @ColorInt annotation to getPrimaryColor

---

app/src/main/res/values/themes.xml

Status bar colour is based on `colorPrimaryDark` which we were not setting.

[NO-JIRA] Theme status bar

---

Backpack/src/androidTest/java/net/skyscanner/backpack/spinner/BpkSpinnerTest.kt
Backpack/src/main/java/net/skyscanner/backpack/spinner/BpkSpinner.kt
UNRELEASED.md

~PoC to check if this works with the app's tests.~
Tested on the app's codebase and tests now run fine.

[NO-JIRA] Disable Spinner animations during tests

---

app/src/main/java/net/skyscanner/backpack/demo/stories/IconsAdapter.kt
app/src/main/java/net/skyscanner/backpack/demo/stories/IconsStory.kt

Adds a toast on click of icon item. 
+ [x] Tests

Toast on icon click

---

Backpack/build.gradle
UNRELEASED.md
app/build.gradle
build.gradle

This is required to update the react native version of `backpack-react-native` to 0.60.4
+ [x] Tests

[BPK-2749] Bump appcompat to 1.0.2

---

Backpack/src/main/java/net/skyscanner/backpack/calendar/BpkCalendar.kt
Backpack/src/main/java/net/skyscanner/backpack/spinner/BpkSpinner.kt
CONTRIBUTING.md
app/build.gradle
app/src/androidTest/java/net/skyscanner/backpack/docs/DocsRegistry.kt
app/src/androidTest/java/net/skyscanner/backpack/docs/GenerateScreenshots.kt
app/src/androidTest/java/net/skyscanner/backpack/docs/RemoteScreenGrab.kt
app/src/main/AndroidManifest.xml
app/src/main/java/net/skyscanner/backpack/demo/ComponentDetailActivity.kt
app/src/main/java/net/skyscanner/backpack/demo/ComponentDetailFragment.kt
app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
app/src/main/java/net/skyscanner/backpack/demo/data/ExampleBpkCalendarController.kt
app/src/main/java/net/skyscanner/backpack/demo/stories/DefaultCalendarStory.kt
app/src/main/res/layout/fragment_nav_bar.xml
scripts/ci-tests.sh
scripts/generate_screenshots.sh
scripts/screenshot-server.py

This is a quick overview of how the script works:
- Builds and install `app-internal` and `app-test-internal`
- Starts a python `http` server listening for screenshot requests
- Runs tests in the emulator specifying that only `GenerateScreenshots` test should run.
- `GenerateScreenshots` runs two tests for every `story`, one for light and one for dark mode.
- Tests will prepare the view for screenshots and call the python server, that will then run adb to take the screenshot and save to the docs folder.
+ [x] Tests
+ [x] Docs (either update …

[NO-JIRA] Automate screenshots

---

Backpack/src/main/java/net/skyscanner/backpack/dialog/BpkDialog.kt
Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/AlertDialogImpl.kt
Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/BpkDialogImpl.kt
UNRELEASED.md
app/src/main/java/net/skyscanner/backpack/demo/stories/DialogStory.kt

Implemented to `setCanceledOnTouchOutside` method in BpkDialog to disabling closing when clicking outside for ALERT type.
+ [x] Tests

[BPK-3760] Avoided dismissing the dialog when setCanceledOnTouchOutside is false

---

Backpack/src/main/java/net/skyscanner/backpack/calendar/view/MonthView.kt
Backpack/src/main/java/net/skyscanner/backpack/calendar/view/WeekdayHeaderView.kt
UNRELEASED.md

Adding acessibility lables to weekday header view. Will fix the date views in a seprate PR
+ [x] Tests

add a11y labels to calendar header

---

CONTRIBUTING.md

A minor fix for the CONTRIBUTION.md file where there was a missing `"` character - which when used would produce a new line in the terminal

Add missing character

---

Backpack/build.gradle
Backpack/gradle-maven-push.gradle
build.gradle

This is abandoned and no longer maintained, therefore removing it. We already contain all the maven publish plugins for publishing instead. Confirmed publishing still works both locally and internally.
+ [ ] Tests

KOA-4581 Remove dcendents plugin

---

Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarControllerTest.kt
build.gradle

This also includes removing a usage of spy. This was an issue with this version prior to the minSdk 24 change, however it was simple to replace this with the fake usage as we already had a fake implementation in place for this test anyways.
+ [x] Tests

KOA-4582 Upgrade mockito android to 3.9.0

---

.idea/compiler.xml
.idea/runConfigurations.xml
Backpack/src/androidTest/java/net/skyscanner/backpack/nudger/BpkNudgerTest.kt
app/src/main/res/menu/settings.xml

Small thing I've noticed while testing accessibility - the settings option didn't have a label.
+ [x] Tests

Add accessibility label

---

backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComponentUsageDetector.kt
backpack-lint/src/test/java/net/skyscanner/backpack/lint/check/BpkComponentUsageDetectorTest.kt
dangerfile.js

The lint check now supports all other components where there is a platform/material equivalent
+ [x] Tests

KOA-4630 Expand lint check to support all components

---

Backpack/src/main/java/net/skyscanner/backpack/starrating/BpkInteractiveStarRating.kt
Backpack/src/main/java/net/skyscanner/backpack/starrating/BpkStarRating.kt
Backpack/src/main/java/net/skyscanner/backpack/starrating/internal/BpkStarRatingBase.kt
Backpack/src/main/res/drawable/bpk_star_rating.xml
Backpack/src/main/res/values/attrs.xml
UNRELEASED.md
app/src/main/res/layout/fragment_star_rating_default.xml
app/src/main/res/layout/fragment_star_rating_interactive.xml
app/src/main/res/layout/fragment_star_rating_max.xml
app/src/main/res/layout/fragment_star_rating_values.xml
app/src/main/res/values/strings.xml
docs/InteractiveStarRating/README.md
docs/StarRating/README.md

The star rating component was lacking accessibility - the interactive component was not possible to be controlled while using talkback. This adds accessibility support to both the static and interactive rating control by adding a new `accessibilityStatus` attribute to be set by consumers. For the interactive component there is a big difference between Android 11/sdk version 30 and below as a new API was added to improve announcements for controls.
(sorry the video + audio is massively out of sync - thank Android Studio for that)
https://user-images.githubusercontent.com/1529791/122533410-72941800-d019-11eb-9c34-23c2fc5e6f97.mp4
https://user-images.githubusercontent.com/1529791/122533402-7031be00-d019-11eb-8606-3d9934aa61ec.mp4
https://user-images.githubusercontent.com/1529791/122533413-732 …

KOA-3596 Improve accessibility for star rating component

---

Backpack/build.gradle
Backpack/lint-baseline.xml
app/build.gradle
app/lint-baseline.xml
lint.xml

This sets up a more strict lint config to spot errors sooner and keep our code quality high. I've setup warnings to be treated as errors and ignored a few issues that we're not interested in. 
All current issues are added to a baseline and will be fixed separately.
I originally took the configuration from the app which was already treating many things as an error that are usually just warnings, but then decided to make it simpler and treat warnings as errors in general, while ignoring the few issues we actually don't care about. It is not possible to share the lint config with a separate project or have multiple lint config files, so even if we were to create a script to copy the file into the project the app couldn't then define some of their exclusions for specific files that are …

KOA-4677 Setup lint config

---

.github/workflows/ci.yml

Based on the [documentation](https://github.com/ReactiveCircus/android-emulator-runner) we should be able to significantly speed up things if we use snapshot caching. Try that.
+ [x] Tests

Add AVD snapshot caching

---

Backpack/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarMonth.kt
UNRELEASED.md

Calendar2 was failing to correctly create the label for any month which had less days than the current day. 
For example, if it tried formatting February on 30th of any month then the label would come off as March. This was due to using a `Date()` without resetting the day(date) value, thus the formatter incorrectly interpreting this as the next month. 
The fix is to reset the `Date()` object to a well know day. In order to avoid TZ issues I've set it up as 2.
Adding new automated test cases will require a discussion around the design of the component.
+ [ ] …

Fix for calendar2 not formatting months with less days than the current day

---

CONTRIBUTING.md

Added instructions on how to create an SDCard on OSX. This was preventing contributors from running the screenshot tests. 
The change is basically an instruction on how to run `hdiutil` which would create an sdcard image which is usable by android.
+ [x] Tests

Add alternative to mksdcard instructions for OSX

---

app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
app/src/main/java/net/skyscanner/backpack/demo/stories/ComposeStory.kt
app/src/main/java/net/skyscanner/backpack/demo/stories/TabStory.kt
app/src/main/res/layout/fragment_tabs.xml

Added a new `TabStory` which allows having tabs for entries. Also added the option to add a compose story without much boilerplate.
+ [ ] Tests

KOA-4749 Add compose tab

---

.github/workflows/ci.yml

Currently when screenshots fail we try to upload an archive containing the results. However, due to running 4 flavours, and defining the same name for the zipped artifact the results get overwriten. 
This PR adds the matrix variant name to the screenshot testing artifact. Which would allow us to upload all falures.
+ [ ] Tests
_If you are curious about how we review, please read through the [code review …

Enable uploading all failure artifacts from screenshots

---

.github/workflows/ci.yml

Currently jobs time out after 6 hours. However most jobs finish after 15 minutes with some outliers getting closer to 30 minutes. Setting a default timeout to 45 minutes should be enough to cover some of the longer builds without wasting too much CI time for when CI is hanging.
+ [x] Tests

Set build timeout on CI

---

.github/workflows/ci.yml

This PR enables commenting on a PR if the screenshot tests fail. 
One comment per failing flavour will be posted, specifying the paths to the screenshots that have failed. It does not add protection agains having all screenshots failing. 
+ [x] Tests

Comment on a PR when screenshot tests fail

---

scripts/lint-staged-ktlint.sh

Fixing issues on the fly means there might be unintended changes. It also meant that splitting up changes into various commits was impossible as all files were added to the commit. Only check for ktlint errors and throw an error instead.
+ [x] Tests

Remove autofix behaviour from ktlint git prehook

---

app/src/main/java/net/skyscanner/backpack/demo/compose/ThemeStory.kt
backpack-compose/CHANGELOG.md
backpack-compose/UNRELEASED.md
backpack-lint/src/main/java/net/skyscanner/backpack/lint/IssueRegistry.kt
backpack-lint/src/main/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetector.kt
backpack-lint/src/test/java/net/skyscanner/backpack/lint/check/BpkComposeComponentUsageDetectorTest.kt
dangerfile.js

Replicated the lint check we had in place for the existing view system to detect usage of non-compose components
+ [x] Tests

KOA-4792 Add lint check for compose component usage

---

Backpack/src/main/java/net/skyscanner/backpack/button/BpkButton.kt
UNRELEASED.md

When using a button with the loading property set in xml the button was crashing due to a stackoverflow exception. Ensure we set the button colour in the constructor instead of the button lazy initialisation
+ [x] Tests

KOA-5024 Fix loading button crash

---

.github/dependabot.yml
.github/release-drafter.yml
.github/workflows/pr.yml

JS & github actions dependencies generally don't affect anything for the consumers, so we shouldn't include them in the changelog. The only exception to this is backpack dependencies which include token changes. these should be part of the changelog, so creating a separate config for them.
+ [x] Tests
If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REVIEW_GUI …

Exclude js and github actions from changelog

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/radiobutton/BpkRadioButton.kt

Selectable is the better usage for a RadioButton and will provide a better experience for accessibility
+ [x] Tests

KOA-4927 Use correct selectable modifier for BpkRadioButton

---

gradle-maven-push.gradle

Snapshot versions are not published to maven central and therefore don't require the signing configuration. This is useful for publishing locally to test changes in the app
+ [x] Tests

Skip signing task for snapshot versions

---

dangerfile.js

The compose module code lives in the kotlin folder, rather than java
+ [x] Tests

Fix danger check for compose components

---

app/src/androidTest/java/net/skyscanner/backpack/compose/spinner/BpkSpinnerTest.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImpl.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/spinner/BpkSpinner.kt
docs/compose/Spinner/README.md

Figma & other platforms use small, large & xl spinner sizes - to ensure there's no confusion and sizes match across platforms rename them before people adopt the new spinner.
+ [x] Tests

Rename spinner sizes to match Figma and other platforms

---

gulpfile.js

`del` was recently bumped in #1126 - during this major bump `del` had changed how they export modules to be in ESM format instead of CommonJS, for some reason CI didn't fail when this automated PR was raised, even though there was an error which now causes new running of `npm run build` to fail.
This PR solves that issue! For now as migrating the full JS to ESM modules is a big task and we probably want to bump the version for security purposes, I have updated the import to use the CommonJS format as per here https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c 
This will unblock the breakage in `main` for any external users or Skyscanner users contributing to the codebase.
+ [ ] Check this if you have read and followed the [contributing …

[NO JIRA]: Patch del version bump build issue

---

.github/workflows/release.yml
buildSrc/build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

An upgrade of Kotlin broke dokka generation. This required an upgrade of the gradle wrapper and an explicit dependency onto dokka to avoid a version clash
Also moved the dokka build before the publish step, so we can avoid a half released state in the future
+ [x] Tests

Fix dokka generation

---

gradle-maven-push.gradle

The compose module was in the kotlin sourceset, rather than java which meant we didn't include the sources when publishing
+ [x] Tests

KOA-5679 Include kotlin sourceset when publishing

---

app/src/main/java/net/skyscanner/backpack/demo/compose/ButtonsStory.kt
app/src/main/res/values/strings.xml
backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImplTest.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/BpkButton.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/button/internal/BpkButtonImpl.kt

Add BpkButton constructor with image, text and content description. Requirement identified [here](https://skyscanner.slack.com/archives/C01V743QEM7/p1690377143020019).

Add bpkbutton content description

---

backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarRangeSelectionTests.kt
backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarSelection.kt
backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarStateMachine.kt

When selecting the whole month for a month that is only partially in the range of selectable dates, the entire month is selected.
This means that changing the selection to a range of dates is more difficult as the selectable dates aren't obvious.
Now with this change only the months that are selectable in the month are selected.
| Calendar | Current selection | New selection |
| -------- | -------- | -------- |
| ![calendar](https://github.com/Skyscanner/backpack-android/assets/141921186/d8aafcd7-bede-40a8-9501-05ab1859aefe) | ![old_month_selection](https://github.com/Skyscanner/backpack-android/assets/141921186/eaae3899-4f3f-423d-a687-49ddc6006ea3) | ![new_month_selection](https://github.com/Skyscanner/backpack-android/assets/141921186/ba098220-0104-4ba6-a79f-f0a2525746e6) |
+ [ ] Check …

OGM-1968 Update month selection to only select days in calendar range

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt

Fixes a UI issue where the content is drawn on top of the toolbar instead of behind it, this prevents the shadow from being displayed when the content has a background. To fix i added a z index of -1f which is less than the default that is applied to the app bar (0f), causing the bar to be drawn over the content.
| Before | After |
| --- | ----------- |
| ![Screenshot_20231002_133455](https://github.com/Skyscanner/backpack-android/assets/26006896/22c8ae83-41ec-4dac-b04c-dc6bd6ae8a27) | ![Screenshot_20231002_133520](https://github.com/Skyscanner/backpack-android/assets/26006896/e9c03d5e-545b-4c8d-8272-74bb5e22338a) |

Set TopNavBar zIndex to 1

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/textfield/internal/BpkTextFieldImpl.kt

Before this change the accessibility announcements for text field were disconnected - placeholder was selectable separately and not announced as part of the text field - if you swiped through items on the screen it would often focus on the placeholder, rather than the text field, making it impossible to interact with the field
+ [ ] Tests

Fix accessibility for text field

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSection.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt

Add `heading` property for the BpkText instance inside the `BpkSectionHeading` and `BpkTopNavBar`, for better screen reader experience
Note: The heading property is intended for screen readers and is not visible to the user.
+ [x] Tests

Add `heading` property for AppSearchModal and TopNavBar

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/modal/BpkModalState.kt

The show/hide function was using a fixed delay. This wasn't working correctly when the animation speed is set to a different value/disabled as the animation would finish at a different point as the delay. This resulted in unexpected behaviour when animation speed was different to the default
+ [ ] Tests

LMN-790 Fix modal show/hide duration

---

build.gradle

Changing the githooks path sometimes broke the path for the app, meaning that the githooks for the main app weren't run anymore. This changes the githooks to just copy the file and use the standard folder, rather than changing the hookspath.
+ [ ] Tests

Switch githooks to standard git hook path

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/snippet/internal/BpkSnippetImpl.kt

[RALP-4859](https://skyscanner.atlassian.net/browse/RALP-4859)
improves accessiblity by adding heading semantic to snippet heading. This makes the screenreader specify when reading a heading that the heading is a heading
+ [ ] Tests

RALP-4859 add heading semantic to snippet heading

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/sectionheader/internal/BpkSectionHeaderImpl.kt

[RALP-4860](https://skyscanner.atlassian.net/browse/RALP-4860)
improves accessiblity by adding heading semantic to section header heading. This makes the screenreader specify when reading a heading that the heading is a heading
+ [ ] Tests

RALP-4860 add heading semantic to section header heading

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/imagegallery/BpkImageGalleryCarousel.kt

[RALP-4861](https://skyscanner.atlassian.net/browse/RALP-4861)
Previously the screenreader could move focus from the image to the page indicator element, this caused repeated information to be read out to the user which is potentially confusing. The page indicator gives no additional info on top of what is already provided by the narration from the image so best approach is to make the indicator invisible to the user
+ [ ] Tests
If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_RE …

RALP-4861 make page indicator invisible to screenreader

---

.github/workflows/_build.yml
.github/workflows/label-check.yml
.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/release.yml

Using the latest ubuntu image for the github runners but using the specific YAML label instead of `latest`
All available images: https://github.com/actions/runner-images?tab=readme-ov-file#available-images

RALP-4865 Use ubuntu-22.04 instead of ubuntu-latest

---

app/src/main/java/net/skyscanner/backpack/demo/compose/BottomSheetStory.kt
app/src/main/res/values/strings.xml
backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkModalBottomSheetTest.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkModalBottomSheet.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/internal/BpkModalBottomSheetImpl.kt
docs/compose/BottomSheet/README.md

This PR introduces a new parameter to `BpkModalBottomSheet` called `titleContentDescription`. This parameter allows developers to provide a custom content description for the title of `BpkModalBottomSheet`. It enables developers to override the default content description, allowing customisation of the text read by screen readers in accessibility mode (e.g., to correct pronunciation issues).
+ [x] Tests

Enable custom content description for the bottom sheet title

---

app/src/main/java/net/skyscanner/backpack/demo/compose/AppSearchModalStory.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModal.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkAppSearchModalImpl.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalContent.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSection.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkShortcuts.kt

As we are having issue with the current location issue, we believe this issue is coming from this changes, so we reversing it
[Screen_recording_20240712_142014.webm](https://github.com/user-attachments/assets/a9d85df6-0214-4c3b-8eac-b93a75e4496f)
…selected (#2041)"
This reverts commit 0421c2d55ac8029d4c0bd8ece532b41a01969405.
+ [x] Tests

Revert - BpkAppSearchModal execute hide animation 

---

app/src/main/java/net/skyscanner/backpack/demo/compose/CardListStory.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/cardlist/rail/BpkRailCardList.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/cardlist/rail/internal/BpkRailCardListImpl.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/sectionheader/BpkSectionHeader.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/sectionheader/internal/BpkSectionHeaderImpl.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/snippet/BpkSnippet.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/snippet/internal/BpkSnippetImpl.kt
docs/compose/CardList/README.md
docs/compose/SectionHeader/README.md
docs/compose/Snippet/README.md

https://skyscanner.atlassian.net/browse/MUON-474
This PR adds an optional parameter to enable/disable `Heading accessibility tag` into BpkSnippet, BpkSectionHeader, and BpkRailCardList.
| | Recording|
| - | - |
| No header activated| <video src="https://github.com/user-attachments/assets/93d3388e-c135-49d7-99eb-40e03842b35e" width="400">|
| Section Header enabled | <video src="https://github.com/user-attachments/assets/3986a554-166f-4e1d-bcae-b7843a2b38f4" width="400">|
| Section Header and Snippet enabled. This last one is set though CardList content parameter | <video src="https://github.com/user-attachments/assets/dca0704c-81e9-42be-92b2-963d2d263858" width="400">|
+ [x] Check this if you have read and followed the [contributing …

[MUON-474] - Add Header tag as optional parameter into BpkSnippet, BpkSectionHeader, and BpkRailCardList

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarGrid.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarSpaceCell.kt

DON-800
Add crossfade to calendar day cell.
Based on [discussions](https://skyscanner.slack.com/archives/C07LH0LRCAK/p1727262745607979?thread_ts=1727167165.640119&cid=C07LH0LRCAK) with designer and product, change `BpkCalendarSpaceCell` to not show selection.
https://github.com/user-attachments/assets/6b7ede40-0a90-4605-80a2-8c1177844db6
https://github.com/user-attachments/assets/9a5c6f10-f6ae-464a-a485-98307bff6d2a
+ [ ] Tests
If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REV …

DON-800 Calendar day cell animations

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/BpkGraphicPromo.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/internal/BpkGraphicPromoImpl.kt

https://skyscanner.atlassian.net/browse/MUON-624
Exposing `interactionSource` so we could customize ripple animation to match the old cards in the Homescreen
+ [ ] Tests

[MUON-624] - Expose interactionSource to support custom animations

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt

Crossfade is being applied every time date price label changes which results to the whole calendar flickering
here is results before and after taking this crossfade out
|Before|After|
|-|-|
+ [ ] Tests

nojira remove cross fade from BpkCalendarDayCell

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/BpkGraphicPromo.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/internal/BpkGraphicPromoImpl.kt

https://skyscanner.atlassian.net/browse/MUON-625?atlOrigin=eyJpIjoiMjM1MTIxNDAzODJiNDE5YWFhOTQxOTVlMjc5NTM1ODMiLCJwIjoiaiJ9
To keep consistency with the clicking animations on homepage, we need to modify the backpack component, admitting an optional parameter to customise the clicking animation to override the current behaviour. 
+ [X] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/main/CONTRIBUTING.md)
+ [X] Component `README.md`
+ [X] Tests

[MUON-625] Added parameter animationIndicationNode in BpkGraphicPromo to enable customisation of clicking animation

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/BpkGraphicPromo.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/internal/BpkGraphicPromoImpl.kt

Just changing the order of two lines to keep the rounded corners after animation
| Before | Now |
|--------|-----|
| ![image](https://github.com/user-attachments/assets/1bafe41d-3d5a-496d-af4b-0330ab94f047) | ![image](https://github.com/user-attachments/assets/4a4e09d9-bcc1-4ed5-a077-bfef277ba62e) |
+ [X] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/main/CONTRIBUTING.md)
+ [X] Component `README.md`
+ [X] Tests

[MUON-625] Homepagehero click animation

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/select/internal/BpkSelectImpl.kt

Currently, the bpk selects scroll state only remember where the last scroll position. This cause an issue that the selector would not focus on the selected index before the user interacts with it. Here we want to make sure it always scroll to selected index when the drop-down menu open
|Current Production| Fix in this PR |
|-|-|
+ [ ] Tests

[DON-999] add scroll to selected index to backpack select

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/horizontalnav/BpkHorizontalNav.kt

https://skyscanner.atlassian.net/browse/PAN-3258
+ [ ] Tests

PAN-3258: Update BpkHorizontalNav component

---

.github/workflows/_build.yml

During the recent channge to the workflows #2195 to use a github app over default github token, it was missed that the screenshot update and commits were missed being tested as these hadn;t changed during this process.
We recently found via backpack-ios that with the new setup for our org this causes commiting to the branch fails when updating screenshots.
To solve this we replicate the same fix from [backpack-ios](https://github.com/Skyscanner/backpack-ios/pull/2167/commits/7eb653480aceee221fae3dede6c160e22259f5e7)
This fix:
- Generates our token
- Supplies it to our repo setup
- Updates the git config to be the bot author

[NO JIRA]: Fix commit automations for CI

---

.github/workflows/_build.yml

This PR is a workaround for the Android Tests stage, which is failing because the emulator is not terminating and causing a timeout.
Here, we got the same issue reported:
https://github.com/ReactiveCircus/android-emulator-runner/issues/385
We also used this workaround:
https://github.com/devinbileck/bisqremote_Android/commit/da1b4167d282a5ff2451bf1993da8e3ee12f4d3a
+ [ ] Tests

ralp/no-jira Add workaround hanging Android Tests

---

.github/workflows/release.yml

This PR updates the documentation deploy step to utilise the `personal_token` field instead of `deploy_key` as SSH key from the automated user is not allowed under new security setup for github.com/skyscanner.
Using it this way and with this name aligns across all the Backpack repos to ease maintenance and readability
See:
[Backpack iOS](https://github.com/Skyscanner/backpack-ios/blob/main/.github/workflows/release.yml#L137-L144)
[Backpack Web](https://github.com/Skyscanner/backpack/blob/main/.github/workflows/main.yml#L146-L154)

Update release.yml to align with other Backpack repos

---

backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarController.kt

Currently the app craches when device is locked due to `CalendarParams` is not `Serializable` 
Please include a description of the changes you are introducing and some screenshots if appropriate.
Please ensure your pull request title is clear as it will be used to generate the changelog.
Add `major`, `minor` or `patch` label depending on the change according to [semver](semver.org) or `skip-changelog` if the change shouldn't be added to the changelog (e.g. a change to a test or documentation)
-->
+ [ ] Tests
If you are curious about how we review, please read through the …

 no_jira fix Calendar crash after lock device

---

.github/dependabot.yml

Right now dependabot is adding the default semver labels, which leads to our Dependabot pr's to be failing because we do use semver labels for identifying libary changes.
See https://github.com/dependabot/dependabot-core/issues/3465

Avoid default dependabot semver labels

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarDayCellTestTag.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/CalendarDayCellTestTag.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt

This pull request refactors the `CalendarDayCellTestTag` enum by moving it from an internal scope to a dedicated file and updates its usage accordingly. This change improves code organization and reusability.
* Created a new file, `CalendarDayCellTestTag.kt`, and moved the `CalendarDayCellTestTag` enum to this file to make it more modular and accessible.
* Removed the inline definition of `CalendarDayCellTestTag` from `BpkCalendarDayCell.kt` and replaced it with an import statement referencing the new file. [[1]](diffhunk://#diff-087353321220a26429372597e00c53bc6d943457c41afcceba1e3404c1eb0735R57) [[2]](diffhunk://#diff-087353321220a26429372597e00c53bc6d943457c41afcceba1e3404c1eb0735L284-L290)
+ [x] Check this if you have read and followed the [contributing …

[DON-1368] move CalendarDayCellTestTag

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/skeleton/BpkSkeleton.kt

Align with iOS on the delay in [BpkShimmer](https://github.com/Skyscanner/backpack-ios/blob/4440205add3648fcf8ab8c70ae17a374f416d690/Backpack-SwiftUI/Skeleton/Classes/BPKShimmer.swift#L50)
https://github.com/user-attachments/assets/4835915f-4ee6-4097-b536-8b609b015ab9
https://github.com/user-attachments/assets/846e1b8d-a098-47f2-a0ed-4e0728019e7e
Change the `transitionSpec` in the `BpkCalendarDayCell` to only delay when going from `Loading` to another case (Text/Icon) 
+ [ ] Tests
If you are curious about how we review, please read through the [code review …

DON-1469 Tweak animations

---

app/src/main/java/net/skyscanner/backpack/demo/compose/SwitchStory.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/switch/BpkSwitch.kt
docs/compose/Switch/README.md

This pull request introduces enhancements to the `BpkSwitch` component in the Backpack Compose library, including new functionality, improved flexibility, and updated documentation. The most notable changes are the addition of a new example, conditional rendering for text content, and adjustments to spacing and alignment.
* Added conditional rendering of the `BpkText` content in `BpkSwitch` to ensure it is only displayed when the `text` parameter is not empty. A `Spacer` is also added for consistent spacing when text is present. 
* Removed the padding on the `Modifier` for the switch alignment to simplify layout customization. 
* Added an example in the `Switch` README to demonstrate the use of an annotated string with styled text in the `BpkSwitch` component. …

fix bpkswitch when content is empty

---

app/src/main/java/net/skyscanner/backpack/demo/data/CalendarStoryType.kt
backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarAccessibilityLabelTests.kt
backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarCell.kt
backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarDayCellTestTag.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt
docs/compose/Calendar2/README.md

Reverts Skyscanner/backpack-android#2290
This was marked as `minor` but included breaking changes.
Marking _this_ one as `patch` as it will return the release to not having breaking changes compared to 67.14.0

Revert "[DON-1385] change selection mode single to support dynamic accessbility"

---

Backpack/src/main/java/net/skyscanner/backpack/navbar/BpkNavBar.kt
Backpack/src/main/res/values/attrs.xml

AppCompat's Toolbar has a `navigationContentDescription` which our consumers have tried to use with no success.
Therefore, I believe we have to make a custom attribute that then gets passed down to it internally.
I did try accessing the AppCompat one but it is private.
Consumers should update their layouts from, for example
```
app:navBarIcon="@drawable/bpk_native_android__back"
app:navigationContentDescription="@string/key_accessibility_navigateup"
```
to
```
app:navBarIcon="@drawable/bpk_native_android__back"
app:navBarActionContentDescription="@string/key_accessibility_navigateup"
```
+ [ ] …

DON-1626 Create custom navBarActionContentDescription 

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkHotelMapMarker.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkIconMapMarker.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPointerMapMarker.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPriceMapMarker.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPriceMapMarkerV2.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/utils/ComposeToBitmap.kt

https://skyscanner.atlassian.net/browse/PAN-4316
There are some differences between [design](https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=8191-8904&p=f&t=zDhfRNLe9b1rpXkK-0) and actual [implementation](https://www.skyscanner.design/latest/components/map/compose-Z0sCXGGA).
So we'd like to remove the markers which should be deprecated and deprecated them firstly.
discuss: https://skyscanner.slack.com/archives/C0JHPDSSU/p1752223047085589
- Deprecate `BpkPriceMapMarker`, user can use `BpkPriceMapMarkerV2` to instead.
- Deprecate `BpkIconMapMarker`  and `BpkHotelMapMarker`, user can use `BpkPoiMapMarker` to instead.
- Deprecate `BpkPointerMapMarker`, user can use `BpkLocationMapMarker` to instead.
- Refresh bitmap of `BpkPriceMapMarkerV2` when prefix icon was …

PAN-4316: Deprecated some old map markers.

---

Backpack/src/main/java/net/skyscanner/backpack/navbar/BpkNavBar.kt
app/src/main/java/net/skyscanner/backpack/demo/stories/NavBarStory.kt

This PR is to exposing the title color and collaspe background color to the consumer, as the carhire dayview need this to have the same ui as before 
+ [ ] Tests

DON-1923 enable title color and collaspe background color to consumer

---

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/CalendarDayCellTestTag.kt
backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/data/CalendarCell.kt

[DON-1968] Refactor moved CalendarDayCellTestTag from internal package
This PR moves a missed file out of the internal package to public.
+ [ ] Tests
[DON-1968]: https://skyscanner.atlassian.net/browse/DON-1968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DON-1968] Refactor moved CalendarDayCellTestTag from internal package
