Skyscanner/backpack-android

.travis.yml, Backpack/build.gradle, app/build.gradle, gulpfile.js, release.js
To fix the failing build
solution from https://github.com/travis-ci/travis-ci/issues/8651
=> [NoJira] fix travis build

Backpack/src/main/res/values/backpack.color.xml, gulpfile.js, release.js, templates/BackpackColor.njk
Add license to files created by us, update copyright and title
=> [BPK-1265] update license

package-lock.json, package.json, release.js
if the response is not a 200
If the user is not part of the org
=> [BKP-1262] add step to check owners during release

README.md
Just need a grammar language check
=> [skip ci][NoJira] docs update

.idea/modules.xml, Backpack/src/main/res/values/backpack.text.xml, CHANGELOG.md, README.md, app/src/androidTest/java/net/skyscanner/backpack/BpkResources.kt, app/src/main/res/layout/activity_main.xml, gulpfile.js, package-lock.json, package.json, templates/BackpackText.njk
=> [BPK-1244] Add support for Backpack text styles

.idea/modules.xml, Backpack/src/main/res/values/backpack.radii.xml, app/src/androidTest/java/net/skyscanner/backpack/BpkResources.kt, app/src/main/java/net/skyscanner/backpack/MainActivity.kt, app/src/main/res/drawable/pill_button.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml, gulpfile.js, templates/BackpackRadii.njk
I've also added a coming soon message to the main app as part of the PR
=> [BPK-1243] expose radii on Android

Backpack/src/main/res/values/backpack.elevation.xml, CHANGELOG.md, README.md, app/build.gradle, app/src/androidTest/java/net/skyscanner/backpack/BpkResources.kt, app/src/main/res/layout/activity_main.xml, gulpfile.js, templates/BackpackElevation.njk
Update the Readme and Changelog from previus PR
Add Elevation tokens
Add simple card to show off elevation and radii
=> [BPK-1246] add elevation tokens

app/build.gradle, build.gradle, package.json, release.js
=> [NoJira] update release script

CONTRIBUTING.md, cookiecutter.json, {{cookiecutter.pkg_name}}/build.gradle, {{cookiecutter.pkg_name}}/src/androidTest/java/net/skyscanner/backpack/{{cookiecutter.pkg_name}}/{{cookiecutter.component_name}}Test.kt, {{cookiecutter.pkg_name}}/src/main/AndroidManifest.xml, {{cookiecutter.pkg_name}}/src/main/java/net/skyscanner/backpack/{{cookiecutter.pkg_name}}/{{cookiecutter.component_name}}.kt, {{cookiecutter.pkg_name}}/src/main/res/values/attrs.xml, {{cookiecutter.pkg_name}}/src/main/res/values/style.xml
Cookiecutter application. Use the following command to generate a new component:
`cookiecutter .`
=> [No-JIRA] Cookiecutter application for new components

Backpack/build.gradle, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/TextFragment.kt, app/src/main/res/layout/fragment_text.xml, package-lock.json, settings.gradle, text/build.gradle, text/src/androidTest/java/net/skyscanner/backpack/text/BpkTextTest.kt, text/src/main/AndroidManifest.xml, text/src/main/java/net/skyscanner/backpack/text/BpkText.kt, text/src/main/res/values/attrs.xml
This adds the TextComponent
here's what it looks like 
I'm happy with everything but the tests, I spent way too much time trying to figure out how to get the font family from a text view and I failed miserably
=> [BPK-1845] add text component

CHANGELOG.md, README.md, UNRELEASED.md, decisions/README.md, decisions/TEMPLATE.md, docs/Badge/README.md, docs/Panel/README.md, docs/Text/README.md
This adds readmes to the different components and improves consistency with the backpack monorepo
=> [BPK-1827] add readmes to components

Backpack/src/main/java/net/skyscanner/backpack/badge/BpkBadge.kt, Backpack/src/main/java/net/skyscanner/backpack/panel/BpkPanel.kt, Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt, Backpack/src/main/res/values/attrs.xml, app/src/main/res/layout/fragment_panel.xml, docs/Panel/README.md
I've fixed some of the linting errors and compilation warnings as part of this PR too
=> [BPK-1901] Remove bpk prefix and fix linting errors

Backpack/build.gradle, README.md
Fixing the publishing configuration.
1. Add missing publishing plugin to library
2. Convert dependency to all lowercase
=> [BPK-1915] Add plugin for publishing

app/build.gradle, app/src/main/java/net/skyscanner/backpack/demo/BackpackDemoApplication.kt
Adding [Stetho](http://facebook.github.io/stetho/)  for inspecting layouts
=> [No-JIRA] Add stetho inspector for layouts

.eslintrc, package-lock.json, package.json
Also updated:
- `bpk-svgs`
- `bpk-tokens`
- `svg2vectordrawable`
No changes from `npm run build` so im happy with the updates.
=> [NOJIRA] Move deps to dev deps

package.json
Package-lock already has this version so this is just a formality (see https://github.com/Skyscanner/backpack-android/blob/master/package-lock.json#L7316)
=> [nojira] Closes #68

release.js
Added a task in release script to update version number in `README.md`
=> [No-JIRA] Update version in readme file during release

app/src/main/res/layout/fragment_all_icons.xml, app/src/main/res/layout/fragment_badge.xml, app/src/main/res/layout/fragment_button.xml, app/src/main/res/layout/fragment_icons.xml, app/src/main/res/layout/fragment_panel.xml, app/src/main/res/layout/fragment_radii.xml, app/src/main/res/layout/fragment_text.xml, app/src/main/res/values/styles.xml
This just center aligns all srtory layouts (except card) so they all look the same.
=> [NO-JIRA] Adjust story layouts

Backpack/src/androidTest/java/net/skyscanner/backpack/spinner/BpkSpinnerTest.kt, Backpack/src/main/java/net/skyscanner/backpack/spinner/BpkSpinner.kt, Backpack/src/main/res/values/attrs.xml, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/res/layout/fragment_spinner.xml, app/src/main/res/layout/fragment_spinner_small.xml, docs/Spinner/README.md
I'll add snapshot testing in a different PR.
=> [BPK-1969] Add Spinner

app/src/main/java/net/skyscanner/backpack/demo/MainActivity.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/res/layout/activity_component_list.xml, app/src/main/res/layout/component_list_content.xml, app/src/main/res/layout/component_list_header.xml
Made it look more like android config views, added click feedback and merged all itens in a single RecyclerView to fix the weird scroll behaviour we have at the moment.
=> [NO-JIRA] Improve layout and usability of stories list

CONTRIBUTING.md, app/src/main/java/net/skyscanner/backpack/demo/ComponentDetailActivity.kt
Adds developer shortcuts for toggle toolbar and layout direction
- Hide/Un-hide toolbar: Shift + T
- Toggle layout direction:  Shift + D
=> Bpk 1946 hide toolbar and rtl toggle

docs/Badge/README.md, docs/Button/README.md, docs/Card/README.md, docs/Dialog/README.md, docs/Panel/README.md, docs/Spinner/README.md, docs/Switch/README.md, docs/Text/README.md
Relative paths are nicer, but they don't work when we embed the readmes in the docs site.
=> [No JIRA] Make links absolute

app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
=> [No-JIRA] Sorting stories in demo

Backpack/src/main/java/net/skyscanner/backpack/button/BpkButton.kt
=> [Bpk-2088] Button size bugfix

Backpack/src/androidTest/java/net/skyscanner/backpack/gradient/BpkGradientsTest.kt, Backpack/src/main/java/net/skyscanner/backpack/gradient/BpkGradients.kt, app/src/androidTest/java/net/skyscanner/backpack/gradient/BpkGradientsTest.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/GradientStory.kt, docs/Gradient/README.md
Updates API for gradient
- Moves from factory pattern to using a constructor
- Preserves deprecated API and provides replacement method.
=> [No-JIRA] Update API for BPKGradient

app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/ButtonStory.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/CalendarStory.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/DialogStory.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/Story.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/SubStory.kt
Using the kotlin's `infix` function style to create stories in the app.
=> [No-JIRA] infix functions for stories

Backpack/src/main/res/drawable-nodpi/bpk_speaker.xml, UNRELEASED.md, package-lock.json, package.json
=> [BPK-2210] New speaker icon

Backpack/src/main/res/drawable-nodpi/bpk_social_like.xml, UNRELEASED.md, package-lock.json, package.json
=> [BPK-2212] New social like icon

app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/ColorAdapter.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/ColorStory.kt, app/src/main/res/layout/color_item.xml, app/src/main/res/layout/fragment_all_colors.xml
=> BPK-1927 Add story for colours

app/src/main/AndroidManifest.xml, app/src/main/java/net/skyscanner/backpack/demo/BpkBaseActivity.kt, app/src/main/java/net/skyscanner/backpack/demo/ComponentDetailActivity.kt, app/src/main/java/net/skyscanner/backpack/demo/SettingsActivity.kt, app/src/main/java/net/skyscanner/backpack/demo/ShakeListener.kt, app/src/main/java/net/skyscanner/backpack/demo/components/SettingsThemeOption.kt, app/src/main/java/net/skyscanner/backpack/demo/data/SharedPreferences.kt, app/src/main/res/layout/activity_settings.xml, app/src/main/res/layout/component_settings_theme_option.xml, app/src/main/res/menu/settings.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/themes.xml
=> [BPK-2246] Add settings page and theme switcher

Backpack/src/main/java/net/skyscanner/backpack/calendar/BpkCalendar.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarController.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/CalendarView.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ExampleBpkCalendarController.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/ColoredCalendarStory.kt, app/src/main/res/layout/fragment_calendar_colored.xml, app/src/main/res/values/strings.xml
- Use case: preserve state but update colors/calendar content.
- Solution: Introduced CalendarUpdateCallback so the Calendar can be updated via the controller
=> Colored calendar update mechanism with example

build.gradle
=> update dependency versions

Backpack/src/main/res/values/backpack.animation.xml, gulpfile.js, package-lock.json, templates/BackpackAnimation.njk
=> BPK-2259 Add animation tokens

Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarController.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/MonthView.kt
- removed single selection drawing
- use null inbound date for single selection
=> Cleanup calendar single selection

.travis.yml, notify.sh
Experrimental PR. Do not merge.
=> no-jira travis notifications

Backpack/src/main/java/net/skyscanner/backpack/util/BpkInterceptor.kt
=> [No-JIRA] Fix highlights for views with background

Backpack/src/main/java/net/skyscanner/backpack/spinner/BpkSpinner.kt, Backpack/src/main/res/values/attrs.xml, UNRELEASED.md, app/src/main/res/values/themes.xml, docs/Spinner/README.md
=> [BPK-2332] Add theming to spinner

Backpack/src/main/java/net/skyscanner/backpack/calendar/BpkCalendar.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/MonthView.kt, Backpack/src/main/res/values/attrs.xml, app/src/main/res/values/themes.xml, docs/Calendar/README.md
=> [BPK-2334] Add theme support to calendar

decisions/event-listeners-and-state.md
Based on the problems and decision we made on #209 
=> [NO-JIRA] Add listeners decision

Backpack/build.gradle, Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarController.kt, app/build.gradle, app/src/main/java/net/skyscanner/backpack/demo/BackpackDemoApplication.kt, build.gradle, docs/Calendar/README.md
=> Add ThreeTenABP dependency to our calendar instead ThreeTenBP

Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt, app/src/main/res/values/themes.xml
=> No-JIRA bugfix

Backpack/src/main/java/net/skyscanner/backpack/chip/BpkChip.kt, Backpack/src/main/res/drawable/chip_background.xml, Backpack/src/main/res/drawable/chip_selected.xml, Backpack/src/main/res/values/attrs.xml, Backpack/src/main/res/values/style.xml, UNRELEASED.md, app/src/main/res/values/themes.xml
=> [BPK-2333] Add theme to chip

docs/Chip/README.md
=> [BPK-2333] Add theme docs to chip

Backpack/src/main/java/net/skyscanner/backpack/calendar/BpkCalendar.kt, Backpack/src/main/java/net/skyscanner/backpack/util/BpkViewPumpContextWrapper.kt
Remove the usage of `kotlinx.android.synthetic` from the library. [Read more](https://www.reddit.com/r/androiddev/comments/ala9p2/why_kotlinx_synthetic_is_no_longer_a_recommended/)
=> No jira remove kotlin synthetic

app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/ElevationStory.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/SpacingStory.kt, app/src/main/res/layout/fragment_elevation.xml, app/src/main/res/layout/fragment_spacing.xml
Add stories for Elevation and Spacing tokens
=> BPK-1928 Add spacing and elevation stories

.travis.yml
This fails even with no changes, so 🤷‍♂️
=> [NO-JIRA] Add docs redeploy to CI

docs/ARCHITECTURE.md
=> [NO-JIRA] Add arch doc

scripts/lint-staged-ktlint.sh
=> [NO-JIRA] Improve pre commit hook

Backpack/src/main/res/values/backpack.text.xml, UNRELEASED.md, gulpfile.js, templates/BackpackText.njk
=> [BPK-2305] Expose text size tokens

Backpack/src/androidTest/java/net/skyscanner/backpack/text/BpkTextTest.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/util/BpkThemeTest.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/MonthView.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/WeekdayHeaderView.kt, Backpack/src/main/java/net/skyscanner/backpack/dialog/BpkDialog.kt, Backpack/src/main/java/net/skyscanner/backpack/spinner/BpkSpinner.kt, Backpack/src/main/java/net/skyscanner/backpack/util/Lazies.kt, app/src/main/java/net/skyscanner/backpack/demo/BpkBaseActivity.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
Please pay special attention to fields initialisation order
=> [BPK-2523] Removed unnecessary lazies, optimised the necessary lazies

Backpack/src/androidTest/java/net/skyscanner/backpack/text/BpkTextTest.kt, Backpack/src/main/java/net/skyscanner/backpack/button/BpkButton.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/MonthView.kt, Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt, UNRELEASED.md
=> [NO-JIRA] Add method applyTo to BpkText

package-lock.json, package.json
This fixes a vulnerability with js-yaml https://github.com/Skyscanner/backpack-android/network/alerts
=> [NO-JIRA] Bump js-yaml to 3.13.1

Backpack/src/main/res/drawable-nodpi/bpk_face__blank.xml, Backpack/src/main/res/drawable-nodpi/bpk_face__happy.xml, Backpack/src/main/res/drawable-nodpi/bpk_face__sad.xml, UNRELEASED.md, package-lock.json, package.json
=> [BPKR-39] Added new smiley icons face--blank, face--happy, face--sad.

.jirabot.yml, package.json
=> [No-Jira] Added support for Jirabot.

Backpack/src/main/java/net/skyscanner/backpack/button/BpkButton.kt
=> [BPK-2619] Added fix #1 for BpkButton on some devices.

app/src/main/java/net/skyscanner/backpack/demo/BackpackDemoApplication.kt, app/src/main/java/net/skyscanner/backpack/demo/SettingsActivity.kt, app/src/main/java/net/skyscanner/backpack/demo/ThemeApplier.kt
=> Added auto theme applying for demo app.

Backpack/src/main/java/net/skyscanner/backpack/starrating/BpkInteractiveStarRating.kt, UNRELEASED.md, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/InteractiveStarRatingStory.kt, app/src/main/res/layout/fragment_star_rating_interactive.xml
=> Bpk 2707 dev android add user interaction listener to interactive star rating

Backpack/src/main/java/net/skyscanner/backpack/button/internal/BpkButtonBase.kt, UNRELEASED.md, app/src/main/res/layout/fragment_button_link.xml
=> [NO-JIRA] Fix white button text colour bug

Backpack/src/main/res/drawable-nodpi/bpk_aircraft.xml, Backpack/src/main/res/drawable-nodpi/bpk_flight_landing.xml, Backpack/src/main/res/drawable-nodpi/bpk_flight_takeoff.xml, UNRELEASED.md, package-lock.json, package.json
=> [BPK-2714]: New `flight-landing`, `flight-takeoff` and `aircraft` icons.

.travis.yml, scripts/compile-bridges.sh
=> [BPK-2685] Compile native bridges

Backpack/src/main/java/net/skyscanner/backpack/text/BpkTextField.kt, UNRELEASED.md
=> Made BpkTextField open

Backpack/src/main/res/values/backpack.color.xml, UNRELEASED.md, package-lock.json, package.json
=> Update bpk dependencies

Backpack/src/main/java/net/skyscanner/backpack/badge/BpkBadge.kt, Backpack/src/main/res/values/attrs.xml, UNRELEASED.md, app/src/main/res/values/themes.xml, docs/Badge/README.md
=> [BPK-2801] Added themes support and includeFontPadding property support for BpkBadge.

Backpack/src/androidTest/java/net/skyscanner/backpack/tokens/BpkResources.kt, Backpack/src/main/java/net/skyscanner/backpack/gradient/BpkGradients.kt, Backpack/src/main/res/values/backpack.color.xml, UNRELEASED.md, app/src/main/java/net/skyscanner/backpack/demo/data/ExampleBpkCalendarController.kt, package-lock.json, package.json
=> [NO-JIRA] Fix sagano token

Backpack/src/main/res/drawable/border.xml
=> [BPK-3149] Fixed the background for Panel in the dark mode.

Backpack/src/main/java/net/skyscanner/backpack/snackbar/BpkSnackbar.kt
=> [BPK-3140] Fixed the text colour for Snackbar in the dark mode.

app/src/main/java/net/skyscanner/backpack/demo/stories/IconsAdapter.kt
=> [BPK-3136] Fixed the RTL icons displaying.

Backpack/src/main/java/net/skyscanner/backpack/button/BpkButtonLink.kt, Backpack/src/main/java/net/skyscanner/backpack/util/BpkTheme.kt
=> [BPK-3143] Updated the ripple effect on the ButtonLink in the dark mode.

Backpack/src/androidTest/java/net/skyscanner/backpack/chip/BpkChipTest.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/util/ResourcesUtilTest.kt, Backpack/src/main/java/net/skyscanner/backpack/badge/BpkBadge.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/MonthView.kt, Backpack/src/main/java/net/skyscanner/backpack/checkbox/BpkCheckbox.kt, Backpack/src/main/java/net/skyscanner/backpack/chip/BpkChip.kt, Backpack/src/main/java/net/skyscanner/backpack/pagetitle/BpkPageTitle.kt, Backpack/src/main/java/net/skyscanner/backpack/snackbar/BpkSnackbar.kt, Backpack/src/main/java/net/skyscanner/backpack/text/BpkTextField.kt, Backpack/src/main/java/net/skyscanner/backpack/toggle/BpkSwitch.kt, Backpack/src/main/res/layout/bpk_dialog.xml, Backpack/src/main/res/layout/view_bpk_rating_horizontal.xml, Backpack/src/main/res/layout/view_bpk_rating_vertical.xml, Backpack/src/main/res/values/backpack.text.xml, Backpack/src/main/res/values/style.xml, app/src/androidTest/java/net/skyscanner/backpack/dialog/BpkDialogTest.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ExampleBpkCalendarController.kt, app/src/main/res/layout/activity_settings.xml, app/src/main/res/layout/component_list_header.xml, app/src/main/res/layout/fragment_icons.xml, app/src/main/res/layout/fragment_spinner.xml, app/src/main/res/layout/fragment_spinner_small.xml, app/src/main/res/layout/fragment_text_fields.xml, app/src/main/res/values/themes.xml
=> No jira update the colour palette

Backpack/src/main/java/net/skyscanner/backpack/spinner/BpkSpinner.kt, UNRELEASED.md, app/src/main/res/values/themes.xml
=> [BPK-3114] Fix spinner theming

app/src/androidTest/java/net/skyscanner/backpack/dialog/BpkDialogTest.kt
=> [NO-JIRA] Fix build

Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/BpkDialogIcon.kt, Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/DialogWindowLayout.kt, Backpack/src/main/res/drawable/bpk_dialog_bg_bottom.xml, Backpack/src/main/res/drawable/bpk_dialog_bg_icon.xml, Backpack/src/main/res/drawable/bpk_dialog_bg_top.xml, Backpack/src/main/res/values-night/internal.semantic.color.xml, Backpack/src/main/res/values/colors.xml, Backpack/src/main/res/values/internal.semantic.color.xml
=> [BPK-3146] [BPK-3138] Updated the Dialog to support the Dark Mode.

scripts/compile-bridges.sh
Fixes https://github.com/Skyscanner/backpack-react-native/issues/268
+ [x] Tests
=> [NO-JIRA] Fix bridge compilations

app/src/main/res/layout/fragment_spinner.xml
=> [BPK-3139] Updated the sample for BpkSpinner.

Backpack/src/main/res/values/style.xml
=> [BPK-3259] Updated the primary colour to have the Dark Mode support.

Backpack/src/main/java/net/skyscanner/backpack/starrating/internal/BpkStarRatingBase.kt, Backpack/src/main/res/values-night/internal.semantic.color.xml, Backpack/src/main/res/values/internal.semantic.color.xml, UNRELEASED.md
=> [BPK-3258] Updated the color for star ratings.

Backpack/src/main/java/net/skyscanner/backpack/horisontalnav/BpkHorizontalNav.kt, Backpack/src/main/res/values-night/internal.semantic.color.xml, Backpack/src/main/res/values/internal.semantic.color.xml, UNRELEASED.md, app/src/main/res/layout/fragment_horizontal_nav_default.xml, app/src/main/res/layout/fragment_spinner_small.xml
=> [BPK-3147] Implemented the Dark Mode support for the HorizontalNav.

Backpack/src/main/java/net/skyscanner/backpack/chip/BpkChip.kt, Backpack/src/main/java/net/skyscanner/backpack/spinner/BpkSpinner.kt, Backpack/src/main/java/net/skyscanner/backpack/util/BpkTheme.kt, Backpack/src/main/res/color/bpk_chip_background_color.xml, app/src/main/res/layout/fragment_icons.xml
=> Did some final adjustments on the Dark Mode.

Backpack/src/main/java/net/skyscanner/backpack/navbar/BpkNavBar.kt, UNRELEASED.md, package-lock.json, package.json
=> [BPK-3347] Added menu getter to BpkNavBar.

docs/Spinner/README.md
=> Fix outdated doc

Backpack/build.gradle, Backpack/gradle-maven-push.gradle, CONTRIBUTING.md, release.js
=> [BPK-3302] Added Artifactory publishing.

Backpack/src/main/java/net/skyscanner/backpack/badge/BpkBadge.kt, UNRELEASED.md
=> [BPK-3357] Fixed the issue.

Backpack/src/main/res/values-night/backpack.semantic.color.xml, Backpack/src/main/res/values/backpack.color.xml, Backpack/src/main/res/values/backpack.semantic.color.xml, UNRELEASED.md, package-lock.json, package.json
=> No jira update tokens

docs/Dialog/README.md
=> [BPK-3101] Updated the documentation for BpkDialog.

.travis.yml, Backpack/build.gradle, Backpack/gradle-maven-push.gradle, Backpack/src/internal/res/values/backpack.font.xml, Backpack/src/main/java/net/skyscanner/backpack/util/BpkTheme.kt, Backpack/src/main/res/values/style.xml, Backpack/src/oss/res/values/backpack.font.xml, CONTRIBUTING.md, app/build.gradle, package.json, scripts/ci-tests.sh
=> [BPK-3403] Implemented the flavours, updated the publishing script.

.travis.yml
=> Fixed apk deployment on the CI.

Backpack/build.gradle, Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt, Backpack/src/main/res/values/attrs.xml, UNRELEASED.md, app/build.gradle, build.gradle
=> [X-1] Updated AppCompat to 1.1.0

.spelling, Backpack/src/main/java/net/skyscanner/backpack/card/BpkCardView.kt, Backpack/src/main/java/net/skyscanner/backpack/text/BpkTextField.kt, Backpack/src/main/res/values-night/backpack.semantic.color.xml, Backpack/src/main/res/values-night/internal.semantic.color.xml, Backpack/src/main/res/values/backpack.color.xml, Backpack/src/main/res/values/backpack.semantic.color.xml, Backpack/src/main/res/values/internal.semantic.color.xml, UNRELEASED.md, package-lock.json, package.json
=> Bpk 3469 dev android add elevation semantic colours

Backpack/src/internal/res/values/backpack.font.xml
This adds all necessary config to setup relative correctly to the internal build
+ [x] Tests
=> [BPK-3406] Update internal font theming

scripts/generate_screenshots.sh
=> [NO-JIRA] Use demo mode for consistent screenshots

Backpack/src/main/java/net/skyscanner/backpack/calendar/BpkCalendar.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarController.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/MonthAdapter.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/MonthFooterAdapter.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/CalendarView.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/WeekdayHeaderView.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ExampleBpkCalendarController.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/FooterViewCalendarStory.kt, app/src/main/res/layout/fragment_calendar_footer_view.xml
=> [BPK-3774] Enable calendar footer view

CONTRIBUTING.md
Was gonna do the actual card but it looks like it's already been done. It says we need nvm instructions but they're already there. So I fixed some grammar stuff instead.
=> [BPK-3781] Grammar fixes

.travis.yml, babel.config.js, dangerfile.js, meta.json, package-lock.json, package.json
This will prevent adding more files without license from now on.
+ [x] Tests
=> [BPK-3436] Add danger

.travis.yml
=> [NO-JIRA] Fail Travis redeploy if non-200-http response

.travis.yml
Basically https://github.com/Skyscanner/backpack-ios/pull/790, but for Android. I've added the token to the secrets for Travis (for now), and also to this repo (for when we migrate to GitHub Actions).
=> [No Jira] Change curl to point to GitHub instead of Travis

CONTRIBUTING.md, scripts/generate_screenshots.sh
I'm not sure if this is actually an error, but I think it is?
=> [NO-JIRA] Fix avd name

Backpack/src/main/java/net/skyscanner/backpack/calendar/BpkCalendar.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/model/CalendarColoring.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarController.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/HighlightedDaysAdapter.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/presenter/MonthAdapter.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/CalendarView.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/HighlightedDaysMonthFooter.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/MonthView.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/WeekdayHeaderView.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ExampleBpkCalendarController.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/FooterViewCalendarStory.kt
=> Calendar auto format.

.github/pull_request_template.md, .github/workflows/ci.yml, .jirabot.yml, Backpack/build.gradle, CONTRIBUTING.md, docs/ARCHITECTURE.md, docs/Badge/README.md, docs/BarChart/README.md, docs/Button/README.md, docs/ButtonLink/README.md, docs/Calendar/README.md, docs/Checkbox/README.md, docs/Chip/README.md, docs/FloatingActionButton/README.md, docs/HorizontalNav/README.md, docs/InteractiveStarRating/README.md, docs/NavBar/README.md, docs/Rating/README.md, docs/Snackbar/README.md, docs/Spinner/README.md, docs/StarRating/README.md, docs/Switch/README.md, docs/TextField/README.md, docs/TextSpans/README.md, docs/Toast/README.md
=> [BPK-4401]: Migrate to main branch

Backpack/src/main/java/net/skyscanner/backpack/dialog/BpkDialog.kt, Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/BpkDialogIcon.kt, UNRELEASED.md, app/src/androidTest/java/net/skyscanner/backpack/dialog/BpkDialogTest.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/DialogStory.kt, docs/Dialog/README.md
=> Moved from BpkDialog.Icon.colorRes to BpkDialog.Icon.color

app/src/main/res/layout/fragment_fab.xml, docs/FloatingActionButton/README.md
=> Added contentDescription docs to BpkFab.

Backpack/gradle-maven-push.gradle
=> Updated Artifactory publishing

Backpack/build.gradle, app/build.gradle, app/src/main/java/net/skyscanner/backpack/demo/ComponentDetailActivity.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/ColoredCalendarStory.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/DefaultCalendarStory.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/DisabledCalendarStory.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/LabeledCalendarStory.kt
Remove dependency to kotlin-android-extensions. It is now deprecated and we were only using it in a few places. I also noticed the calendar view crashing with labels as it was trying to create labels for invalid dates.
+ [ ] Tests
=> [KOA-4571] Remove kotlin android extensions

app/build.gradle, build.gradle
Updated all dependencies that can be updated without any issues and created tickets for others.
+ [ ] Tests
=> [KOA-4574] Update dependencies

Backpack/src/main/res/layout/view_bpk_rating_vertical.xml
The vertical rating component had a rendering issue that wasn't caught by the screenshot testing when upgrading to ConstraintLayout 2.0
+ [ ] Tests
=> Fix vertical rating component

Backpack/src/main/res/drawable-nodpi/bpk_car_door.xml, Backpack/src/main/res/drawable-nodpi/bpk_car_door_sm.xml, UNRELEASED.md, package-lock.json, package.json
Looks like dependabot didn't help us with these, so updated manually. 
+ [ ] Tests
=> BPKR-181 Add new car door icon

docs/Card/README.md
Added an accessibility section to the card documentation.
+ [x] Tests
=> KOA-4542 Add accessibility documentation for cards

Backpack/build.gradle, Backpack/lint-baseline.xml, Backpack/src/androidTest/java/net/skyscanner/backpack/badge/BpkBadgeTest.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/HighlightedDaysMonthFooter.kt, Backpack/src/main/java/net/skyscanner/backpack/calendar/view/MonthView.kt, Backpack/src/main/res/layout/view_bpk_tab.xml, lint.xml
This adds fixes/ignores for all lint errors in the backpack module. The app module is to come.
+ [x] Tests
=> KOA-4678 Fix lint errors in backpack module

.husky/pre-commit, package-lock.json, package.json
As part of the husky dependabot update the husky checks broke as the upgrade required some breaking changes - this fixes the issues.
+ [x] Tests
=> Fix husky upgrade

Backpack/build.gradle, app/build.gradle, backpack-lint/build.gradle, build.gradle
=> Improved dependabot compatibility.

Backpack/build.gradle, UNRELEASED.md
This broke the published version as backpack-common can't be resolved (as it's not publish)
+ [x] Tests
=> Remove backpack-common dependency

app/src/main/java/net/skyscanner/backpack/demo/MainActivity.kt, app/src/main/java/net/skyscanner/backpack/demo/StoriesRecyclerViewAdapter.kt, app/src/main/java/net/skyscanner/backpack/demo/StoryItemDecoration.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/SubStory.kt, app/src/main/res/drawable/item_divider.xml, app/src/main/res/layout/component_list_content.xml, app/src/main/res/values/strings.xml
Add an indicator on the component list for components available in compose. Also fixed a bug with dividers disappearing that bothered me for ages.
+ [x] Tests
=> KOA-4775 Add compose indicator

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColor.kt, backpack-compose/tokens.gradle.kts, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt
=> Koa 4745 dev android create static color token generation task for compose

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkBorderRadius.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColor.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkElevation.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkSpacing.kt, backpack-compose/tokens.gradle.kts, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkDimensions.kt
=> Koa 4784 dev android create dynamic color token generation task for compose

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkFontSize.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkLetterSpacing.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkLineHeight.kt, backpack-compose/tokens.gradle.kts, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkFormat.kt, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkTextUnits.kt
=> Added text tokens generation

build.gradle
Downgraded maps as there were some issues on the app side
+ [x] Tests
=> Downgrade maps

build.gradle
This reverts commit 4d864977830720bff9ab5c1d6e73bc0d0ba6740f.
There's an issue with RN in 1.4.0
+ [x] Tests
=> Revert "Bump appcompat from 1.3.1 to 1.4.0 (#781)"

docs/Calendar2/README.md
=> Improved docs for Calendar 2

.github/pull_request_template.md, .spelling, README.md
=> Updated the README.md

package-lock.json, package.json
Updated lint-staged and updated usage in pre-commit hook.
+ [x] Tests
=> Update lint-staged to 12.1.5

gulpfile.js, package-lock.json, package.json
Version 0.6.0 has a vulnerability and the location changed, so dependabot wasn't updating it
+ [x] Tests
=> Update xmldom to 0.8.0

package-lock.json, package.json, release.js
Releaseit was reading the version from package.json & git tags and then ignoring the version we supplied. Remove the package.json version as we're not publishing anyways (similar to iOS) and set separate tags for compose & existing backpack packages.
+ [x] Tests
=> Fix release script for compose

README.md
=> Updated Compose readme

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkFontSize.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkTypography.kt, backpack-compose/tokens.gradle.kts, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkTextStyles.kt, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkTextUnits.kt
Generate the compose typography styles, rather than creating them programmatically.
+ [x] Tests
=> KOA-4826 Generate compose typography styles

Backpack/src/test/java/net/skyscanner/backpack/util/TestStateMachine.kt, app/src/main/java/net/skyscanner/backpack/demo/stories/LoadingButtonStory.kt, build.gradle
=> Downgrade coroutines

Backpack/src/main/java/net/skyscanner/backpack/button/BpkButton.kt, UNRELEASED.md
This is needed for the RN button bridging
+ [x] Tests
=> KOA-4896 Add size property to button

.github/workflows/label-check.yml
Turn out a space between the labels broke the check
+ [x] Tests
=> Fix label check

.github/workflows/release.yml, .gitignore
=> Added CI secure enviroment

.github/workflows/release.yml
We need to set the environment to be able to access environment secrets
+ [x] Tests
=> KOA-4973 Set publishing environment in release job

.github/workflows/release.yml
This will ensure the apk is building correctly before anything is published - allowing us to rerun the release process in case something goes wrong
+ [x] Tests
=> KOA-4974 Move apk build before publishing

.github/workflows/_build.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, Backpack/src/main/java/net/skyscanner/backpack/TestFile.kt
We need write permissions on pull requests for screenshot & build steps to be able to report the status correctly/comment on PRs
+ [x] Tests
=> Tweak CI permissions for build steps

CONTRIBUTING.md
The old command wasn't working on newer OS versions
+ [ ] Tests
=> Update sd card creation guide

CONTRIBUTING.md
=> Add guide for getting push rights

CONTRIBUTING.md
We no longer deploy branches, but to test changes developers can publish locally instead
+ [x] Tests
=> Update guide for deploying branches/locally

app/src/androidTest/java/net/skyscanner/backpack/compose/dialog/BpkDialogTest.kt
Bye bye reflection
+ [x] Tests
=> Simplify dialog test code

.nvmrc
CI may use a different npm or node version to locally, which may cause failures on CI when a newer version of npm/node is released due to package-lock inconsistencies. Lock the version to avoid automatic updates.
+ [x] Tests
=> Lock nvm version to avoid CI failures

Backpack/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
=> Removed deprecated dayOfWeekAccessibilityText and dateAccessibilityText properties from CalendarParams

.github/release-drafter.yml
Using the right label might help.
+ [x] Tests
=> Fix github actions label exclusion

CONTRIBUTING.md
Our contribution guide was lacking details - particularly around screenshot testing & docs screenshots. Added some more details & clarification to make it easier to understand.
+ [x] Tests
=> Improve contribution guide

app/build.gradle, app/src/main/java/net/skyscanner/backpack/demo/data/Tokens.kt, build.gradle
Create list for tokens in demo app, so we can easily add a demo for this.
+ [x] Tests
=> KOA-5414 Provide list of tokens

app/src/main/java/net/skyscanner/backpack/demo/compose/SpacingStory.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt
=> Added Compose demo screen for spacing

app/src/main/java/net/skyscanner/backpack/demo/compose/ElevationStory.kt, app/src/main/java/net/skyscanner/backpack/demo/compose/SpacingStory.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/res/values/strings.xml
=> KOA-5405 Add Compose elevation screen to the demo app

app/src/main/java/net/skyscanner/backpack/demo/compose/RadiiStory.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, app/src/main/res/layout/fragment_radii.xml
=> KOA - 5406 Added a Compose demo screen for radii

Backpack/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarRangeSelectionTests.kt, app/build.gradle, backpack-compose/build.gradle.kts, build.gradle, buildSrc/build.gradle.kts
Bumped kotlin & compose compiler version. Compose itself we can't update yet as we need to bump the sdk version for that which we're not ready to do yet.
+ [x] Tests
=> KOA-5427 Bump kotlin and compose compiler version

docs/view/Card/README.md
=> Add props documentation for cards

.github/workflows/record_screenshots.yml
=> Added default action for screenshot recording on the CI

.github/workflows/record_screenshots.yml, app/src/androidTest/java/net/skyscanner/backpack/fab/BpkFabTest.kt
=> Updated snapshots recording code

Backpack/src/main/java/net/skyscanner/backpack/horisontalnav/BpkHorizontalNav.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/horizontalnav/BpkHorizontalNav.kt
Updated supported things to new tokens. Also deprecated alternate styling (it's still being used in the app)
+ [x] Tests
=> KOA-5531 Update horizontal nav to new colour tokens

.github/workflows/record_snapshots.yml, app/src/androidTest/java/net/skyscanner/backpack/fab/BpkFabTest.kt
=> Breaking the tests.

.github/workflows/record_snapshots.yml, app/src/androidTest/java/net/skyscanner/backpack/fab/BpkFabTest.kt
=> Breaking the tests

.github/workflows/record_snapshots.yml, app/src/androidTest/java/net/skyscanner/backpack/fab/BpkFabTest.kt
=> Breaking tests.

app/src/main/java/net/skyscanner/backpack/demo/data/Tokens.kt
The colours screen started crashing since we added the deprecation message.
+ [x] Tests
=> Fix color token screen

Backpack/src/main/java/net/skyscanner/backpack/skeleton/BpkCircleSkeleton.kt, Backpack/src/main/java/net/skyscanner/backpack/skeleton/BpkHeadlineSkeleton.kt, Backpack/src/main/res/drawable/bpk_skeleton_bg.xml, Backpack/src/main/res/drawable/bpk_skeleton_shimmer_bg.xml, Backpack/src/main/res/values-night/backpack.semantic.color.xml, Backpack/src/main/res/values-night/internal.semantic.color.xml, Backpack/src/main/res/values/backpack.semantic.color.xml, Backpack/src/main/res/values/internal.semantic.color.xml, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/sleketon/BpkSkeleton.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/internal/BpkButtonColors.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/internal/BpkSkeletonColors.kt, package-lock.json, package.json
=> KOA-5579 Update skeleton to semantic colours

Backpack/src/main/java/net/skyscanner/backpack/barchart/internal/ChartDrawable.kt, Backpack/src/main/java/net/skyscanner/backpack/barchart/internal/ChartPopupDrawable.kt, Backpack/src/main/java/net/skyscanner/backpack/text/BpkTextInputLayout.kt, android-configuration.gradle
=> Koa-5610 Bumped target SDK to 33

.github/workflows/_build.yml, .github/workflows/record_snapshots.yml
=> Improve CI caching

Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/presenter/BpkCalendarControllerTest.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/presenter/HighlightedDaysAdapterTest.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/view/NonDrawnDaysOffset.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/calendar/view/WeekdayViewHeaderTest.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/chip/BpkChipTest.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/starrating/BpkInteractiveStarRatingTests.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/text/BpkTextInputLayoutTest.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/text/BpkTextTest.kt, Backpack/src/androidTest/java/net/skyscanner/backpack/util/TestContext.kt, app/build.gradle, app/src/androidTest/java/net/skyscanner/backpack/BpkSnapshotTest.kt, app/src/androidTest/java/net/skyscanner/backpack/barchart/BpkBarchartTests.kt, app/src/androidTest/java/net/skyscanner/backpack/calendar/BpkCalendarTest.kt, app/src/androidTest/java/net/skyscanner/backpack/calendar2/BpkCalendarTest.kt, app/src/androidTest/java/net/skyscanner/backpack/compose/dialog/BpkDialogTest.kt, app/src/androidTest/java/net/skyscanner/backpack/dialog/BpkDialogTest.kt, app/src/androidTest/java/net/skyscanner/backpack/map/internal/BpkMapMarkerTest.kt, app/src/androidTest/java/net/skyscanner/backpack/navbar/BpkNavBarTest.kt, app/src/androidTest/java/net/skyscanner/backpack/snackbar/BpkSnackbarTests.kt, build.gradle
=> KOA-5611 Remove usages of ActivityTestRule

.github/workflows/record_snapshots.yml, CONTRIBUTING.md
android/blob/main/CONTRIBUTING.md)
+ [ ] Tests
=> Fixed snapshots generation scripts

README.md
This was pointing to a CI pipeline that doesn't exist anymore, so was constantly failing.
+ [ ] Tests
=> Fix CI badge and compose version info

.github/workflows/record_snapshots.yml
=> Fix yml formatting

CONTRIBUTING.md, docs/compose/Slider/README.md, scripts/generate-component.py, templates/component/Component.kt, templates/component/README.md, templates/component/Story.kt, templates/component/Test.kt
Created a script to setup the basic parts required for creating new components (component, demo app sample, test, readme).
Sample output/steps:
```
Enter the name of the component:
BpkSpaceShip
Enter the package name of the component, or leave empty for spaceship:
space
Create compose component structure for space.BpkSpaceShip?
[Y/n]: y
Creating compose component structure...
Created BpkSpaceShip.kt
Created SpaceShipStory.kt
Created BpkSpaceShipTest.kt
Created README.md
To include the component in the demo app add the following line to the ComponentRegistry.kt COMPONENT list in alphabetic position:
"SpaceShip" composeStory { SpaceShipStory() }
To add it to the screenshot generation add the following line to the DocsRegistry.kt screenshots list in alphabetic position: …
```
=> Create script for setting up new components

templates/component/README.md
=> Use correct screenshot folder

docs/compose/BottomNav/README.md
=> Fix error in url

app/src/androidTest/java/net/skyscanner/backpack/BpkSnapshotTest.kt, app/src/androidTest/java/net/skyscanner/backpack/bottomsheet/BpkBottomSheetTest.kt, app/src/androidTest/java/net/skyscanner/backpack/snackbar/BpkSnackbarTests.kt
=> Fix snapshot flakiness

docs/compose/BarChart/README.md, docs/compose/Slider/README.md
Some URLs were wrong. Fixed that.
+ [x] Tests
=> Fix Readme screenshots

.nvmrc, Backpack/src/main/java/net/skyscanner/backpack/chip/internal/Utils.kt, Backpack/src/main/res/drawable/bpk_bg_rating_badge.xml, Backpack/src/main/res/drawable/chip_outline_background.xml, Backpack/src/main/res/values/backpack.radii.xml, CHANGELOG.md, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkBorderRadius.kt, package-lock.json, package.json
Renamed pill to xl and updated all references
+ [x] Tests
=> KOA-5838 Rename border radius pill to xl

app/src/main/java/net/skyscanner/backpack/demo/compose/IconsStory.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkIcon.kt, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkIcons.kt
=> KOA-5642 Cleanup automirror logic

buildSrc/src/main/kotlin/net/skyscanner/backpack/screenshots/ScreenshotTestsServer.kt
=> Fixed the screenshots issue

build.gradle, buildSrc/build.gradle.kts
For some reason dependabot didn't raise these, so bumped manually (after having done in the Skyscanner app).
Also moved to the bom as there's various point releases on some of the dependencies, so this ensures we always stay in sync.
+ [x] Tests
=> Bump Kotlin & Compose

.github/workflows/_build.yml, templates/component/README.md
Noticed danger wasn't giving a status + was failing the build on main
+ [x] Tests
=> Ensure danger only runs on PR and produces output

app/src/androidTest/java/net/skyscanner/backpack/compose/price/BpkPriceTest.kt, app/src/main/java/net/skyscanner/backpack/demo/compose/PriceStory.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/BpkPrice.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/price/internal/BpkPriceImpl.kt, docs/compose/Price/README.md
This is to align with other platforms after a change on others.
+ [x] Tests
=> KOA-5919 Rename lineThroughText to previousPrice on BpkPrice

templates/component/Story.kt
Not all components are sliders.
+ [x] Tests
=> Fix template sample

.github/workflows/_build.yml
=> Ensure app is uninstalled before we attempt to install

.detekt-compose.yml, build.gradle
The original Twitter rules are now forked and maintained on the new fork by the original maintaines.
+ [x] Tests
=> KOA-5924 Switch to new compose detekt fork

app/src/androidTest/java/net/skyscanner/backpack/docs/GenerateScreenshots1.kt, app/src/androidTest/java/net/skyscanner/backpack/meta/StoriesTests.kt, app/src/main/java/net/skyscanner/backpack/demo/meta/Component.kt, app/src/main/java/net/skyscanner/backpack/demo/meta/StoriesRepository.kt, app/src/main/java/net/skyscanner/backpack/demo/meta/ViewStory.kt, app/src/main/java/net/skyscanner/backpack/demo/ui/BpkScarldfold.kt, app/src/main/java/net/skyscanner/backpack/demo/ui/ComponentListScreen.kt, app/src/main/java/net/skyscanner/backpack/demo/ui/ComponentScreen.kt, app/src/main/java/net/skyscanner/backpack/demo/ui/DemoScaffold.kt, app/src/main/java/net/skyscanner/backpack/demo/ui/StoryScreen.kt, meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/Models.kt, meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/References.kt, meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/AbstractStoriesVisitor.kt, meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ComponentsVisitor.kt, meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ComposeStoriesVisitor.kt, meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/visitor/ViewStoriesVisitor.kt, meta-processor/src/main/kotlin/net/skyscanner/backpack/ksp/writer/StoriesWriter.kt
=> Koa 5892 Implement support of custom KSP processor for screenshots

app/src/androidTest/java/net/skyscanner/backpack/compose/navigationbar/BpkTopNavBarTest.kt, app/src/main/java/net/skyscanner/backpack/demo/compose/NavBarStory.kt, app/src/main/java/net/skyscanner/backpack/demo/data/ComponentRegistry.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/BpkTopNavBar.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationbar/internal/BpkTopNavBarImpl.kt
=> Aligned the navIcon argument for NavBar for Compose

.github/workflows/release.yml, package-lock.json, package.json
=> Add supernova as a dependency

.github/dependabot.yml, Backpack/build.gradle, android-configuration.gradle, app/build.gradle, app/src/main/java/net/skyscanner/backpack/demo/BackpackDemoApplication.kt, app/src/main/java/net/skyscanner/backpack/demo/meta/Component.kt, app/src/main/java/net/skyscanner/backpack/demo/meta/ComposeStory.kt, app/src/main/java/net/skyscanner/backpack/demo/meta/ViewStory.kt, backpack-common/build.gradle, backpack-compose/build.gradle, backpack-lint/build.gradle, build.gradle, buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts, dokka.gradle, gradle-maven-push.gradle, gradle/libs.versions.toml, meta-processor/build.gradle
=> KOA 5988 Migrate to gradle central dependency declaration

app/src/main/java/net/skyscanner/backpack/demo/ui/ComponentListScreen.kt
=> Koa-5408 Added a search bar in the demo app

CONTRIBUTING.md
=> [KOA-5970] Add experimentation guidelines

.idea/inspectionProfiles/ktlint.xml, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/icon/BpkIcon.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkIcon.kt, backpack-compose/src/test/kotlin/net/skyscanner/backpack/compose/icon/BpkIconTest.kt, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkIcons.kt, docs/compose/Icon/README.md
Icon names come back from backend - we want to have an option to find these by name. Also ensure the name is the non-formatted name to ensure it's the same across all platforms.
+ [x] Tests
=> KOA-6068 Add option to find icon by name

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/checkbox/BpkCheckbox.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/radiobutton/BpkRadioButton.kt
=> Migrated the Checkbox and RadioButton to MD3

backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt
=> Implemented the fix for Calendar2 weekdays style for some Chinese languages

.nvmrc, package-lock.json, package.json
=> Updated to Node 18

Backpack/src/main/java/net/skyscanner/backpack/snackbar/BpkSnackbar.kt, Backpack/src/main/java/net/skyscanner/backpack/toast/BpkToast.kt, docs/view/Snackbar/README.md, docs/view/Toast/README.md
=> Deprecated the Snackbar & Toast components

Backpack/src/main/res/layout/view_bpk_calendar_header.xml, backpack-common/src/androidTest/java/net/skyscanner/backpack/calendar2/data/CalendarLocalisationTests.kt, backpack-common/src/main/java/net/skyscanner/backpack/calendar2/CalendarParams.kt, backpack-common/src/main/java/net/skyscanner/backpack/calendar2/data/CalendarCell.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarDayCell.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarHeader.kt
=> Calendar accessibility improvements

.github/workflows/release.yml
App centre upload was failing because the silent option is no longer valid. Everything else in the release still worked correctly.
+ [ ] Tests
=> Remove silent publishing option

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/internal/BpkCalendarSpaceCell.kt
=> KOA-6243 Fixed calendar range colour between months

.github/workflows/release.yml
=> Fixed AppCenter upload

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPriceMapMarker.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/modal/BpkModal.kt
=> Tweaks to bpkModal and BpkMapPriceMarker

gradle.properties
=> Fixed the KSP not generating the info due to the bug

Backpack/src/main/java/net/skyscanner/backpack/bottomnav/BpkBottomNav.kt
=> Disabled the custom font of BpkBottomNav for RTL locales

app/src/main/java/net/skyscanner/backpack/demo/compose/MapStory.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkIconMapMarker.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPriceMapMarker.kt
=> Allow consuming of Marker onClick behaviour and set default focused zIndex

.github/workflows/_build.yml
https://github.com/ReactiveCircus/android-emulator-runner/issues/239
+ [ ] Tests
=> Add avd-name in attempt to reduce emulator boot failures

app/src/main/java/net/skyscanner/backpack/demo/compose/AppSearchModalStory.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModal.kt
=> LMN-678 BpkAppSearchModal subtitle annotatedString

.github/workflows/_build.yml
Trying out switching to ubuntu for android tests as this is meant to speed up CI significantly https://github.com/slackhq/circuit/pull/1128
Reduced from 10 to 5 minutes 🚀 
+ [ ] Tests
=> Use ubuntu-latest with baseline profile gen

app/build.gradle, build.gradle, gradle/libs.versions.toml
Turns out the plugin was still being applied.
+ [ ] Tests
=> Remove shot plugin

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/text/BpkText.kt
=> expose inlineContent

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt, buildSrc/src/main/kotlin/net/skyscanner/backpack/tokens/BpkColors.kt
We have no usages - let's not encourage anybody
+ [ ] Tests
=> Remove deprecated colours in compose

.gitignore, Dangerfile.df.kts
Made our danger check messages a bit clearer and added some missing ones.
+ [ ] Tests
=> Improve danger checks

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationtabgroup/BpkNavigationTabGroup.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationtabgroup/internal/BpkNavigationTab.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/navigationtabgroup/internal/BpkNavigationTabGroupImpl.kt
=> added behavioural data support to BpkNavigationTabGroup

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSection.kt
DON-460: Update clickable area for bpksectionItem
=> DON-460: Update clickable area for bpksectionItem

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalContent.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkShortcuts.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/chipgroup/single/BpkSingleSelectChipGroup.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/chipgroup/single/internal/BpkSingleSelectChipGroupImpl.kt
=> No_JIRA add behaviouralEventWrapper to shortcuts

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/bottomsheet/BpkModalBottomSheetState.kt, gradle.properties
=> RALP-4864 Fix bottom sheet recomposition issue

app/src/main/java/net/skyscanner/backpack/demo/compose/AppSearchModalStory.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/BpkAppSearchModal.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkAppSearchModalImpl.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSearchModalContent.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkSection.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/appsearchmodal/internal/BpkShortcuts.kt
Hide Animation is executed when item is selected
https://github.com/Skyscanner/backpack-android/assets/19841948/e2737569-8db9-4279-9197-346808846f5a
+ [ ] Tests
=> NoJira - BpkAppSearchModal execute hide animation when place selected

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/graphicpromotion/internal/BpkGraphicPromoImpl.kt
Eliminating a duplicated line that occurred after merging some commits. 
+ [X] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/main/CONTRIBUTING.md)
+ [X] Component `README.md`
+ [X] Tests
=> [MUON-625] Eliminate duplicated line

android-configuration.gradle, app/src/main/java/net/skyscanner/backpack/demo/compose/StarRatingStory.kt, app/src/test/java/net/skyscanner/backpack/compose/starrating/BpkStarRatingTest.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/starrating/BpkStarRating.kt
=> Fix experimental flag triggering on non-experimental usage

Backpack/src/main/res/values/backpack.semantic.color.xml, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/tokens/BpkColors.kt, package-lock.json, package.json
Updates bpk-foundations-android to adopt the latest changes
+ [ ] Tests
=> [NO JIRA]: Updating foundations to the latest

.github/workflows/_build.yml, .github/workflows/label-check.yml, .github/workflows/pr.yml
Attempting to use a GitHub App for access to the GitHub REST API as a workaround for [limitations with IP allowlisting](https://docs.github.com/en/enterprise-cloud@latest/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/managing-allowed-ip-addresses-for-your-organization#using-github-actions-with-an-ip-allow-list).
+ [ ] Tests
=> SDPLAT-26630: use GH_APP for GitHub REST API

.github/workflows/main.yml, .github/workflows/release.yml
Follow-up to https://github.com/Skyscanner/backpack-android/pull/2195, resolve build errors on `main` branch: https://github.com/Skyscanner/backpack-android/actions/runs/13057467953
+ [ ] Tests
=> SDPLAT-26630: use GH_APP in main.yml

.github/workflows/main.yml
Adds missing GH App usage for release drafter
=> SDPLAT-26630: use GH App in Release Drafter

gradle/libs.versions.toml
Reverts Skyscanner/backpack-android#2171
=> Revert "Bump org.jetbrains.dokka:dokka-gradle-plugin from 1.9.20 to 2.0.0"

backpack-compose/src/androidTest/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarTest.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendar.kt, backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/calendar/BpkCalendarController.kt, docs/compose/Calendar2/README.md
Add an optional callback to observe scrolling in the list of dates. (Which is a list of months).
+ [ ] Tests
=> DON-1319 Add scroll callback to BpkCalendar

package-lock.json, package.json
[NO-JIRA] bump-up bpk-svgs to latest version 20.4.1
+ [ ] Tests
=> [NO-JIRA] bump-up bpk-svgs to latest version 20.4.1

app/src/main/res/values/themes.xml
=> -am migrate missing deprecated token

backpack-compose/src/main/kotlin/net/skyscanner/backpack/compose/map/BpkPriceMapMarkerV2.kt
=> PAN-4378: Remove unused debug logging.

gradle-maven-push.gradle
=> donburi fix dokka publish

backpack-common/src/androidTest/AndroidManifest.xml, backpack-common/src/androidTest/kotlin/net/skyscanner/backpack/configuration/EmptyActivity.kt, backpack-common/src/androidTest/kotlin/net/skyscanner/backpack/configuration/ViewUtilsTest.kt, backpack-common/src/androidTest/res/values/attrs.xml, backpack-common/src/androidTest/res/values/theme.xml, backpack-common/src/main/kotlin/net/skyscanner/backpack/configuration/BpkConfiguration.kt, backpack-common/src/main/kotlin/net/skyscanner/backpack/util/ViewUtils.kt, backpack-common/src/main/res/values/attrs.xml, backpack-common/src/test/kotlin/net/skyscanner/backpack/configuration/BpkConfigurationTest.kt
Add helper function for Views so logger can be called when View is VISIBLE.
+ [ ] Tests
=> DON-2026 Add logger callback to BpkConfiguration

Backpack/lint-baseline.xml, Backpack/src/main/java/net/skyscanner/backpack/bottomnav/BpkBottomNav.kt, Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/BpkDialogImpl.kt, Backpack/src/main/java/net/skyscanner/backpack/dialog/internal/DialogWindowLayout.kt, Backpack/src/main/java/net/skyscanner/backpack/flare/BpkFlare.kt, Backpack/src/main/java/net/skyscanner/backpack/navbar/internal/BpkCollapsingToolbarLayout.kt, Backpack/src/main/java/net/skyscanner/backpack/navbar/internal/BpkToolbar.kt, Backpack/src/main/java/net/skyscanner/backpack/panel/BpkPanel.kt, Backpack/src/main/java/net/skyscanner/backpack/snackbar/internal/SnackbarCustomisationUtils.kt, Backpack/src/main/java/net/skyscanner/backpack/text/BpkText.kt, Backpack/src/main/java/net/skyscanner/backpack/util/Drawables.kt, Backpack/src/main/java/net/skyscanner/backpack/util/Views.kt, android-configuration.gradle, app/lint-baseline.xml, app/src/main/java/net/skyscanner/backpack/demo/stories/IconsStory.kt, app/src/main/java/net/skyscanner/backpack/demo/ui/SettingsThemeOption.kt, gradle/libs.versions.toml
Reverts Skyscanner/backpack-android#2411
We found it caused issues leading to us needing a major version bump
=> Revert "Bump com.google.maps.android:maps-compose from 6.7.2 to 6.8.0"
